"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Msg={role:"user"|"assistant";content:string}; type Conversation={id:string;title:string;messages:Msg[]};
const starters=[["Research","Compare sources and synthesize findings."],["Code","Plan, review, and improve software."],["Leads","Discover and rank business prospects."],["Browser","Use approved tools to get things done."]];
const uid=()=>crypto.randomUUID?.()??Date.now().toString(36);
export default function HomePage(){
 const [chats,setChats]=useState<Conversation[]>([]),[active,setActive]=useState(""),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[mobile,setMobile]=useState(false),[settings,setSettings]=useState(false),[health,setHealth]=useState<"checking"|"online"|"offline">("checking"),bottom=useRef<HTMLDivElement>(null);
 const chat=useMemo(()=>chats.find(c=>c.id===active),[chats,active]);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("nexron-chats")||"[]");if(Array.isArray(x)){setChats(x);if(x[0])setActive(x[0].id)}}catch{}},[]);
 useEffect(()=>{localStorage.setItem("nexron-chats",JSON.stringify(chats));bottom.current?.scrollIntoView({behavior:"smooth"})},[chats]);
 useEffect(()=>{fetch("/api/health").then(r=>setHealth(r.ok?"online":"offline")).catch(()=>setHealth("offline"))},[]);
 const create=()=>{const c={id:uid(),title:"New task",messages:[]};setChats(x=>[c,...x]);setActive(c.id);setMobile(false);setError("")};
 const remove=async(id:string)=>{setChats(x=>x.filter(c=>c.id!==id));if(active===id)setActive(chats.find(c=>c.id!==id)?.id||"");fetch("/api/conversations/"+id,{method:"DELETE"}).catch(()=>{})};
 async function send(){const text=input.trim();if(!text||busy)return;let target=active;if(!target){const c={id:uid(),title:text.slice(0,42),messages:[]};setChats(x=>[c,...x]);setActive(c.id);target=c.id}else setChats(x=>x.map(c=>c.id===target?{...c,title:c.title==="New task"?text.slice(0,42):c.title,messages:[...c.messages,{role:"user",content:text}]}:c));setInput("");setBusy(true);setError("");
 try{const res=await fetch("/api/chat/stream",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text})});if(!res.ok){throw new Error((await res.json().catch(()=>({}))).error||"Request failed")}if(!res.body)throw new Error("Streaming is unavailable");const reader=res.body.getReader(),decoder=new TextDecoder();let buf="",answer="",added=false;
 while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const parts=buf.split("\n\n");buf=parts.pop()||"";for(const ev of parts){const line=ev.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const d=JSON.parse(line.slice(6));if(d.error)throw new Error(d.error);if(d.delta){answer+=d.delta;setChats(x=>x.map(c=>{if(c.id!==target)return c;const msgs=added?c.messages.slice(0,-1):c.messages;added=true;return {...c,messages:[...msgs,{role:"assistant",content:answer}]}}))}}}
 }catch(e){setError(e instanceof Error?e.message:"Something went wrong")}finally{setBusy(false)}}
 return <main className="appShell">
  <aside className={"sidebar "+(mobile?"open":"")}><div className="brand"><span className="mark">N</span><b>Nexron</b><button className="closeSide" onClick={()=>setMobile(false)}>×</button></div><button className="newChat" onClick={create}>＋ New chat</button><div className="history">{chats.map(c=><div className={"historyRow "+(c.id===active?"selected":"")} key={c.id}><button onClick={()=>{setActive(c.id);setMobile(false)}}>{c.title}</button><button className="delete" onClick={()=>remove(c.id)}>×</button></div>)}</div><div className="sideBottom"><span><i className={health}/>{health==="checking"?"Checking systems…":health==="online"?"Systems online":"Backend offline"}</span><small>Free-first routing</small><button className="settingsLink" onClick={()=>setSettings(true)}>⚙ Settings</button></div></aside>
  <section className="main"><header className="topbar"><button className="menu" onClick={()=>setMobile(true)}>☰</button><div><span className="eyebrow">NEXRON AI</span><h1>{chat?.title||"New chat"}</h1></div><div className="topActions"><span className="model">Auto · Free-first</span><button onClick={()=>setSettings(true)}>⚙</button></div></header>
   <div className="chatArea">{!chat||!chat.messages.length?<div className="welcome"><div className="heroMark">N</div><h2>What can I help you accomplish?</h2><p>One workspace for research, coding, lead intelligence, and tool-assisted work.</p><div className="starterGrid">{starters.map(([a,b])=><button key={a} onClick={()=>setInput(a+": ")}><b>{a}</b><small>{b}</small><span>↗</span></button>)}</div></div>:<div className="messages">{chat.messages.map((m,i)=><article key={i} className={"message "+m.role}><div className="avatar">{m.role==="user"?"You":"N"}</div><div className="messageBody"><span className="role">{m.role==="user"?"You":"Nexron"}</span><div className="bubble">{m.content}</div></div></article>)}{busy&&<div className="typing"><i/><i/><i/> Nexron is working…</div>}<div ref={bottom}/></div>}</div>
   <div className="composerWrap"><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message Nexron…" rows={1}/><button onClick={send} disabled={busy||!input.trim()}>↑</button></div><div className="composerMeta">Enter to send · Shift+Enter for newline · Responses may use multiple agents</div>{error&&<div className="error">{error}</div>}</div>
  </section>
  {settings&&<div className="modalBackdrop" onClick={()=>setSettings(false)}><div className="settings" onClick={e=>e.stopPropagation()}><div className="settingsHead"><h2>Settings</h2><button onClick={()=>setSettings(false)}>×</button></div><div className="setting"><b>Connection</b><span className={health}>● {health==="online"?"Backend connected":health==="offline"?"Backend unavailable":"Checking…"}</span></div><div className="setting"><b>Routing</b><span>Automatic · free-first</span></div><div className="setting"><b>Storage</b><span>Local chat history</span></div><p className="settingsNote">Production authentication and persistent server storage are handled by the Nexron backend.</p></div></div>}
 </main>
}