import type { AgentTask, Capability, ChatMessage, ProviderResponse, ToolRequest } from "@nexron/shared";
import type { AIRouter } from "@nexron/ai-router";
import { TaskExecutor } from "@nexron/taskmaster";
import { BUILTIN_AGENTS } from "./specialists.js";
import { CapabilityDispatcher } from "./dispatcher.js";
import type { LeadIntelligenceService } from "@nexron/lead-intelligence";
import type { MemoryStore } from "@nexron/memory";
export interface AgentDefinition{readonly id:string;readonly name:string;readonly capability:Capability;readonly systemPrompt:string;}
export interface AgentContext{readonly messages?:ChatMessage[];readonly signal?:AbortSignal;readonly userId?:string;}
export interface AgentTaskPlanner{plan(input:string,context:AgentContext):Promise<AgentTask[]>;}
export interface AgentToolBridge{execute(request:ToolRequest,signal?:AbortSignal):Promise<unknown>;}
export interface AgentRunResult{readonly tasks:AgentTask[];readonly response:ProviderResponse;}
export class AgentRuntime{
 private readonly executor:TaskExecutor;
 constructor(private readonly router:AIRouter,private readonly planner:AgentTaskPlanner,private readonly tools?:AgentToolBridge,private readonly specialists:readonly AgentDefinition[]=BUILTIN_AGENTS,private readonly leads?:LeadIntelligenceService,private readonly memory?:MemoryStore){
  const dispatcher=new CapabilityDispatcher({specialists, specialistExecutor:{execute:async(task,agent,signal)=>{const messages:ChatMessage[]=[{role:"system",content:agent.systemPrompt},{role:"user",content:typeof task.input==="string"?task.input:JSON.stringify(task.input??{})}];const result=await this.router.complete({messages,capability:task.capability,stream:false},{freeFirst:true,signal});return {...task,status:"completed",output:result.content};}},toolExecutor:tools?{execute:async(task,request,signal)=>{const output=await tools.execute(request,signal);return {...task,status:"completed",output};}}:undefined,leadExecutor:leads?{execute:async(task,signal)=>{const input=task.input as {query?:string;limit?:number};const records=await leads.search({query:String(input?.query??""),limit:input?.limit},signal);return {...task,status:"completed",output:records};}}:undefined});
  this.executor=new TaskExecutor({execute:(task,context)=>dispatcher.execute(task,context.signal)});
 }
 private async contextWithMemory(input:string,context:AgentContext){if(!this.memory||!context.userId)return context;const memories=await this.memory.search(context.userId,input,8);if(!memories.length)return context;const memoryMessage:ChatMessage={role:"system",content:"Relevant saved context:\n"+memories.map(m=>"- "+m.content).join("\n")};return {...context,messages:[memoryMessage,...(context.messages??[])]};}
 private async remember(input:string,result:AgentRunResult,userId?:string){if(!this.memory||!userId)return;await this.memory.save({id:crypto.randomUUID(),userId,content:"Request: "+input+"\nResult: "+result.response.content,createdAt:Date.now()});}
 async run(input:string,context:AgentContext={}):Promise<AgentRunResult>{const enriched=await this.contextWithMemory(input,context);const planned=await this.planner.plan(input,enriched);const tasks=await this.executor.run(planned,{signal:context.signal});const completed=tasks.filter(task=>task.status==="completed");if(!completed.length)throw new Error("Agent run completed without a successful task.");const final=await this.router.complete({messages:[...(enriched.messages??[]),{role:"user",content:"Original request: "+input},{role:"assistant",content:JSON.stringify(completed.map(task=>({id:task.id,title:task.title,output:task.output})))},{role:"user",content:"Synthesize the completed task outputs into the final answer."}],capability:"chat",stream:false},{freeFirst:true,signal:context.signal});const result={tasks,response:final};await this.remember(input,result,context.userId);return result;}
 async *stream(input:string,context:AgentContext={}):AsyncIterable<string>{const enriched=await this.contextWithMemory(input,context);const planned=await this.planner.plan(input,enriched);const tasks=await this.executor.run(planned,{signal:context.signal});const completed=tasks.filter(task=>task.status==="completed");if(!completed.length)throw new Error("Agent run completed without a successful task.");const messages=[...(enriched.messages??[]),{role:"user" as const,content:"Original request: "+input},{role:"assistant" as const,content:JSON.stringify(completed.map(task=>({id:task.id,title:task.title,output:task.output})))},{role:"user" as const,content:"Synthesize the completed task outputs into the final answer."}];let full="";for await(const delta of this.router.stream({messages,capability:"chat",stream:true},{freeFirst:true,signal:context.signal})){full+=delta;yield delta;}if(this.memory&&context.userId)await this.memory.save({id:crypto.randomUUID(),userId:context.userId,content:"Request: "+input+"\nResult: "+full,createdAt:Date.now()});}
}